server:
  port: "5000"
  api_key: ""

database:
  status: true
  host: "postgres"
  port: "5432"
  database: "ATTENDANCE_DB"
  user: "admin"
  password: "Qdafjnftt854!"
  ssl_mode: "disable"

minio:
  endpoint: "minio:9000"
  access_key: "admin"
  secret_key: "Hsjdnvftrmm630!"
  bucket_name: "attendance"
  use_ssl: false

redis:
  host: "redis"
  port: "6379"
  max_connection: 80
  username: ""
  password: "Nfuwebngssajg4357!!"
  database: 0
  tls_config: false

jira:
  url: "https://farchanputra1358.atlassian.net/"
  email: "farchanputra1358@gmail.com"
  token: "ATATT3xFfGF0fg9JdDaqHswU1yYnmk-KSfb6jvPfCRWuaOSIm0xNOhX49Bwv32s5XD2YfdV5TdPKsFQHpIPXswsTJF65XNry-ewFYBFPdSURI4CKw5KXaOCReEpgGLdG_8qTNAuWQsYH_NCh5bOYcyvAJVSjf270qZPl5dDthjzSu1FudMzMzFY=61BEA481"
  project_key: "SCRUM"

ml_service:
  url: "http://ml-service:8001"