version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - deploy_internal
    depends_on:
      - ml-service

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8001:8001"
    networks:
      - deploy_internal
    environment:
      # These will be passed to ML Service to access MinIO via the docker network
      - MINIO_HOST=deploy_minio_1
      - MINIO_PORT=9000
      # Ensure you set these if your credentials differ
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=Hsjdnvftrmm630!
      - MINIO_BUCKET=attendance
      - MINIO_USE_SSL=false

networks:
  deploy_internal:
    external: true
